name: cjmshimlateacher
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.3+3

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^6.1.2
  scrollable_clean_calendar: ^1.5.0
  google_fonts: ^6.2.1
  carousel_slider_plus: ^7.1.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  html: ^0.15.0 # Check for the latest version
  url_launcher: ^6.0.20 # Use the latest version
  video_player: ^2.5.1
  youtube_player_flutter: ^9.1.1
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.13.0
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  fluttertoast: ^8.2.8
  #  syncfusion_flutter_datepicker: ^20.4.50
  pdf: ^3.10.4
  path_provider: ^2.1.1
  open_filex: ^4.6.0
  flutter_screenutil: ^5.9.0
  day_picker: ^2.3.0
  cached_network_image: ^3.4.0
  syncfusion_flutter_datepicker: ^30.1.39
  awesome_dialog: ^3.2.1
  flutter_neumorphic_plus: ^3.4.0
  flutter_cached_pdfview: ^0.4.3
  animated_custom_dropdown: ^3.1.1
  flutter_searchable_dropdown: ^2.0.0
  dropdown_search: ^5.0.6
  searchable_paginated_dropdown: ^1.3.0
  flutter_inappwebview: ^6.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/images/app_logo.png"


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
